### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by ariona** [madhu314/react-native-tabbed-view-pager-android#1]
Hello, Can this handle large number for pages, for example 600 pages without performance issue?

**Comment by madhu314** [comment]
Are you implying that there will be 600 tabs in the activity ?

**Comment by ariona** [comment]
I am sorry, I don't really understand about the activity since i am relatively new to RN and android env. But i have tried this library before https://github.com/race604/react-native-viewpager and it's really can handle large number of page without the performance issue. (i guess it's because using the same method as listview in rendering the page)

**Comment by madhu314** [comment]
Having 600 pages is not recommended, a good design will probably limit it to 15 to 20 pages....If you have lot of content try listview

**Comment by ariona** [comment]
Say, i want to create a Book app. The book has 100 chapter/Pages in it. And the Tab label will be, Chapter I — Chapter II and so on. :) .

I use the library mentioned before, it's only ViewPager but working flawless rendering 600 pages with a lot of content in it. But i really like the scrolling tabs on your lib, and will consider using it 😄

**Comment by madhu314** [comment]
You could give it a shot but I am not very positive about this.
