### ISSUE TITLE
Page inset

### ISSUE THREAD

**Issue by oxyii** [madhu314/react-native-tabbed-view-pager-android#16]
I'm not sure that this project is still alive, but:
looks like tabbed pages are getting the wrong placing and size information. Even in your example in README you can see that the content of tabbed pages is below the middle. Pages go down out the screen exact to the height of TabBar.

**Comment by madhu314** [comment]
I am not actively maintaining this, but PRs are welcome. 🙂
thanks

**Comment by oxyii** [comment]
I’ll try, but I don’t have enough experience for high-quality work in the native

**updated** Please don't close this issue for now

**Comment by madhu314** [comment]
Sure, I will keep it open for a while

**Comment by madhu314** [comment]
hey @oxyii 
you can possibly check the js offset in this file here -- https://github.com/madhu314/react-native-tabbed-view-pager-android/blob/989821d8a0f9009f639866d07286ab5ffacac333/index.js#L165

Also another quick workaround for you would be to add a marginBottom to the containing views equal to the heigh of the tabBar

**Comment by oxyii** [comment]
Yeah! Thank you. I can make workaround for my current project. But I can’t be sure that TabLayout will be the same height for all gadgets and font scales. So I plan to look carefully at your sources and make correct path for me and others

**Comment by oxyii** [comment]
I found solution for me. I'm using [RNN](https://github.com/wix/react-native-navigation) in my project. So after merging [this PR](https://github.com/wix/react-native-navigation/pull/5433) `topTabs` works fine on Android. We can close this issue if nobody else interested it.
