### ISSUE TITLE
Lower Case Tab Names

### ISSUE THREAD

**Issue by andrerfneves** [madhu314/react-native-tabbed-view-pager-android#2]
Hey @madhu314, this package is by far the best native-Android implementation I've come across. I'd like to use it in my project, however I do want to be able to change the styles of the TabName items. How would one go about doing that? 

I could submit a PR, but not super familiar with Android ViewPager to be able to pass style props down to the native level. Let me know your thoughts. If you're busy and can't implement this I can look into submitting a PR myself with some help.

Cheers

**Comment by madhu314** [comment]
Hey @andrerfneves 
So I have tried to support all the Tab customisation available in https://developer.android.com/reference/android/support/design/widget/TabLayout.html

Lower case tabs are not per material spec afaik, thats why there is no such method available to change the text appearance style in TabLayout methods. However TabLayout does support custom view, supporting custom views over the bridge is going to be a big feature request.

Check out https://github.com/AlbertBrand/react-native-android-tablayout , this project has custom tabs implementation, however unlike this project it does not have view pager built in, it should be added separately. There are some examples of the same in the project repo.

Refer https://blog.uncommon.is/react-native-ui-component-for-viewpager-with-tablayout-design-pattern-in-android-74cc18e87afd , explains why I had to create this project in the first place.

If you think you would like to go with this project and need custom tabs feature, Please feel free to submit a PR.

**Comment by andrerfneves** [comment]
Awesome. Thanks for the explanation @madhu314. I went ahead and used it anyways. Will try to create a workaround for font changes at least on my repo and if it works well I'll clean and submit a PR for your package.

**Comment by Noitidart** [comment]
This was a nice topic to learn about this module's native prespective. Thanks all for the work. Going to be using this soon. :)

**Comment by ashokkumar88** [comment]
@andrerfneves how did you put lower case tabnames?

**Comment by Noitidart** [comment]
@ashokkumar88 this one supports lower case tab names - https://github.com/adbayb/react-native-android-kit

**Comment by ashokkumar88** [comment]
cool. Thanks @andrerfneves
