### ISSUE TITLE
error in react-native 0.48.1

### ISSUE THREAD

**Issue by wenjiahui** [madhu314/react-native-tabbed-view-pager-android#4]
createJSModules() in TabbedViewPagerAndroidPackage class  is removed in **react-native 0.48.1**.

**Comment by madhu314** [comment]
@wenjiahui 
I will work on it a couple of days, if you have time, please feel free to send a PR

**Comment by madhu314** [comment]
Addressed in PR #6

install 1.0.3

**Comment by wenjiahui** [comment]
thank you very much for your work
