### ISSUE TITLE
Bug when another component opened and then backed to this one

### ISSUE THREAD

**Issue by davidbilik** [madhu314/react-native-tabbed-view-pager-android#7]
Hello, I am using your library along with https://facebook.github.io/react-native/ . I have a viewpager in one of the tabs and when I push some component over the one with viewpager and then I hit back, viewpager will "break".. it seems that connection between TabLayout and ViewPager is broken or I dont know what.. If I swipe to the side, it keeps stuck between two pages and if I click on any of the tabs, tab get selected but viewpager page do not change.. do you know what may be happening or do you need more info? Thanks very much, nice library by the way

**Comment by madhu314** [comment]
there is a known issue in react native for this

https://github.com/facebook/react-native/issues/13463


I will followup when this is fixed

**Comment by madhu314** [comment]
Seems like this has been addressed here https://github.com/facebook/react-native/pull/14867

I will pickup the same changes in this library as well

**Comment by ashokkumar88** [comment]
@davidbilik seems you are react native navigation. This is a issue in react native navigation and not in this library. The solution is mentioned here https://github.com/wix/react-native-navigation/issues/1317. Check the solution mentioned by @t2n3qqq on the above link.
