### ISSUE TITLE
Adding icons to Tabs

### ISSUE THREAD

**Issue by azeemhassni** [madhu314/react-native-tabbed-view-pager-android#8]
Thanks for this nice project. This is the 2nd time I'm using it in my projects, but this time I need to add icons along with text. 

Do your package supports anything like this?

**Comment by madhu314** [comment]
Not planning on such feature currently

**Comment by azeemhassni** [comment]
OK

**Comment by Noitidart** [comment]
@azeemhassni this one supports icons - https://github.com/adbayb/react-native-android-kit
