### ISSUE TITLE
Tabbed View Pager Doesn't Exist

### ISSUE THREAD

**Issue by shiroze** [madhu314/react-native-tabbed-view-pager-android#9]
Invariant Violation: Native component for TabbedViewPager does not exist

**Comment by madhu314** [comment]
Can you provide more details ?

**Comment by shiroze** [comment]
I use the code same with example but it give me a error value say TabbedViewPager does not exist

**Comment by shiroze** [comment]
I already solve this problem. the problem is because I dont set Link before use them thanks
